from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

from .types import IntentSpec

# Canonical registry of all supported operations and their intent specifications
CANONICAL_INTENT_SPECS: List[IntentSpec] = [
    # ── GH CLI SPECIFICATIONS ──────────────────────────────────────────
    IntentSpec(
        domain="gh",
        operation="pr_review_approve",
        lexical_hints=["approve pr", "approve pull request", "pr review approve", "approve the pr", "approve"],
        required_slots=["pr_number"],
        command_family="gh",
        description="Approve a GitHub pull request",
        doc_topic="gh pr review"
    ),
    IntentSpec(
        domain="gh",
        operation="issue_list",
        lexical_hints=["list issues", "show issues", "open issues", "view issues", "list open issues"],
        required_slots=[],
        command_family="gh",
        description="List issues in the repository",
    ),
    IntentSpec(
        domain="gh",
        operation="issue_create",
        lexical_hints=["create issue", "new issue", "open issue", "submit issue", "report issue"],
        required_slots=["title"],
        command_family="gh",
        description="Create a new issue",
    ),
    IntentSpec(
        domain="gh",
        operation="issue_close",
        lexical_hints=["close issue", "resolve issue", "close the issue"],
        required_slots=["issue_number"],
        command_family="gh",
        description="Close an issue by number",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_diff",
        lexical_hints=["pr diff", "diff for pr", "view diff", "show pr diff", "changes in pr"],
        required_slots=["pr_number"],
        command_family="gh",
        description="View diff for a pull request",
    ),
    IntentSpec(
        domain="gh",
        operation="release_create",
        lexical_hints=["create release", "new release", "publish release", "create a release"],
        required_slots=["tag"],
        optional_slots=["notes"],
        command_family="gh",
        description="Create a new release with tag",
        doc_topic="gh release create"
    ),
    IntentSpec(
        domain="gh",
        operation="gist_list",
        lexical_hints=["list gists", "show gists", "view gists", "my gists"],
        required_slots=[],
        command_family="gh",
        description="List GitHub gists",
    ),
    IntentSpec(
        domain="gh",
        operation="repo_clone",
        lexical_hints=["clone repo", "clone repository", "clone the repo"],
        required_slots=["repo"],
        command_family="gh",
        description="Clone a GitHub repository",
    ),
    IntentSpec(
        domain="gh",
        operation="repo_fork",
        lexical_hints=["fork repo", "fork repository", "fork"],
        required_slots=["repo"],
        optional_slots=["clone"],
        command_family="gh",
        description="Fork a GitHub repository",
        doc_topic="gh repo fork"
    ),
    IntentSpec(
        domain="gh",
        operation="workflow_run_logs",
        lexical_hints=["workflow run logs", "workflow logs", "run logs", "actions run logs", "view workflow run"],
        required_slots=["run_id"],
        command_family="gh",
        description="View logs for a GitHub Actions workflow run",
        doc_topic="gh run view"
    ),
    IntentSpec(
        domain="gh",
        operation="pr_merge",
        lexical_hints=["merge pr", "merge pull request", "rebase pr"],
        required_slots=["pr_number"],
        optional_slots=["strategy"],
        command_family="gh",
        description="Merge a pull request",
        doc_topic="gh pr merge"
    ),
    IntentSpec(
        domain="gh",
        operation="label_list",
        lexical_hints=["list labels", "show labels", "repo labels"],
        required_slots=[],
        command_family="gh",
        description="List repository issue/PR labels",
    ),

    # ── GCLOUD CLI SPECIFICATIONS ──────────────────────────────────────
    IntentSpec(
        domain="gcloud",
        operation="list_addresses",
        lexical_hints=["list static ip", "static ip addresses", "external ip addresses", "list addresses", "static ips"],
        required_slots=[],
        command_family="gcloud",
        description="List external static IP addresses",
        doc_topic="gcloud compute addresses list"
    ),
    IntentSpec(
        domain="gcloud",
        operation="create_firewall_rule",
        lexical_hints=["create firewall rule", "allow port", "firewall rule", "open port in firewall"],
        required_slots=["rule_name", "port"],
        command_family="gcloud",
        description="Create a compute firewall rule",
        doc_topic="gcloud compute firewall-rules create"
    ),
    IntentSpec(
        domain="gcloud",
        operation="cloud_run_logs",
        lexical_hints=["cloud run logs", "service logs", "cloud run service logs", "logs for cloud run"],
        required_slots=["service"],
        command_family="gcloud",
        description="Read logs for a Cloud Run service",
    ),
    IntentSpec(
        domain="gcloud",
        operation="cloud_run_deploy",
        lexical_hints=["deploy to cloud run", "cloud run deploy", "deploy container to cloud run", "deploy service to cloud run"],
        required_slots=["service", "image"],
        command_family="gcloud",
        description="Deploy a container to Cloud Run",
    ),
    IntentSpec(
        domain="gcloud",
        operation="storage_list",
        lexical_hints=["list objects in bucket", "list gcs bucket", "list storage bucket", "storage list", "gcs list"],
        required_slots=["bucket"],
        command_family="gcloud",
        description="List objects in a Google Cloud Storage bucket",
    ),
    IntentSpec(
        domain="gcloud",
        operation="storage_copy",
        lexical_hints=["copy file to gcs", "upload file to bucket", "copy to bucket", "gcs cp", "storage cp", "gsutil cp"],
        required_slots=["source", "destination"],
        command_family="gcloud",
        description="Copy a file to or from a GCS bucket",
    ),
    IntentSpec(
        domain="gcloud",
        operation="iam_policy",
        lexical_hints=["iam policy", "get iam policy", "view iam policy", "project iam policy"],
        required_slots=["resource"],
        command_family="gcloud",
        description="Get IAM policy for a resource",
    ),
    IntentSpec(
        domain="gcloud",
        operation="set_region",
        lexical_hints=["set default compute region", "default region", "set compute region", "configure default region"],
        required_slots=["region"],
        command_family="gcloud",
        description="Set default compute region in gcloud config",
    ),
    IntentSpec(
        domain="gcloud",
        operation="sql_describe",
        lexical_hints=["describe cloud sql", "describe sql instance", "cloud sql instance info", "sql instances describe"],
        required_slots=["instance"],
        command_family="gcloud",
        description="Describe a Cloud SQL instance",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_machine_types",
        lexical_hints=["list machine types", "available machine types", "compute machine types", "machine-types list"],
        required_slots=["zone"],
        command_family="gcloud",
        description="List available compute machine types in a zone",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_instances",
        lexical_hints=["list instances", "list compute instances", "list vms", "show instances", "instances list"],
        required_slots=[],
        optional_slots=["zone"],
        command_family="gcloud",
        description="List compute engine instances",
    ),
    IntentSpec(
        domain="gcloud",
        operation="stop_instance",
        lexical_hints=["stop compute instance", "stop instance", "stop vm", "stop the instance", "shut down instance", "stop dev-server", "stop server"],
        required_slots=["instance"],
        optional_slots=["zone"],
        command_family="gcloud",
        description="Stop a running Compute Engine instance",
        doc_topic="gcloud compute instances stop"
    ),
    IntentSpec(
        domain="gcloud",
        operation="function_logs",
        lexical_hints=["cloud function logs", "function logs", "logs for function"],
        required_slots=["function_name"],
        command_family="gcloud",
        description="View Cloud Function logs",
    ),

    # ── PACMAN / ARCH SPECIFICATIONS ───────────────────────────────────
    IntentSpec(
        domain="pacman",
        operation="query_explicit",
        lexical_hints=["explicitly installed packages", "query explicit", "list explicitly installed", "packages installed by user", "explicit packages"],
        required_slots=[],
        command_family="pacman",
        description="List explicitly installed packages",
    ),
    IntentSpec(
        domain="pacman",
        operation="clean_cache",
        lexical_hints=["clean pacman cache", "clean pacman package cache", "clean package cache", "clean the pacman package cache", "clean cache keeping", "prune pacman cache", "paccache"],
        required_slots=[],
        optional_slots=["retain_versions"],
        command_family="pacman",
        description="Clean package cache keeping recent versions",
        doc_topic="paccache"
    ),
    IntentSpec(
        domain="pacman",
        operation="find_orphans",
        lexical_hints=["orphan packages", "orphaned packages", "find orphans", "list orphaned", "unneeded packages"],
        required_slots=[],
        command_family="pacman",
        description="Find unneeded orphan packages",
    ),
    IntentSpec(
        domain="pacman",
        operation="downgrade_from_cache",
        lexical_hints=["downgrade package", "downgrade a package", "install previous version from cache", "rollback package from cache"],
        required_slots=["package"],
        command_family="pacman",
        description="Downgrade a package from local package cache",
    ),
    IntentSpec(
        domain="pacman",
        operation="mkinitcpio",
        lexical_hints=["rebuild initramfs", "regenerate initramfs", "mkinitcpio", "all presets initramfs"],
        required_slots=[],
        command_family="pacman",
        description="Rebuild initramfs for all presets",
    ),
    IntentSpec(
        domain="pacman",
        operation="reflector",
        lexical_hints=["update pacman mirrorlist", "reflector mirrorlist", "fastest mirrors", "sort mirrors by speed", "pacman mirrorlist"],
        required_slots=[],
        command_family="pacman",
        description="Update mirrorlist sorted by speed using reflector",
    ),
    IntentSpec(
        domain="pacman",
        operation="lsmod",
        lexical_hints=["list loaded kernel modules", "loaded kernel modules", "show loaded kernel modules", "lsmod modules", "display kernel modules"],
        required_slots=[],
        command_family="pacman",
        description="List loaded kernel modules",
    ),
    IntentSpec(
        domain="pacman",
        operation="verify_package_files",
        lexical_hints=["verify package file integrity", "verify package files", "check package integrity", "verify files of package", "pacman -Qk"],
        required_slots=["package"],
        command_family="pacman",
        description="Verify file integrity of an installed package",
    ),
    IntentSpec(
        domain="pacman",
        operation="package_owner",
        lexical_hints=["which package owns", "package owns file", "package owner of", "file belongs to which package"],
        required_slots=["path"],
        command_family="pacman",
        description="Find which package owns a specific file",
    ),

    # ── JOURNALCTL SPECIFICATIONS ──────────────────────────────────────
    IntentSpec(
        domain="journalctl",
        operation="kernel_logs",
        lexical_hints=["show kernel errors", "kernel errors", "kernel logs", "kernel errors in system journal", "kernel logs in journal", "dmesg errors in journalctl", "journalctl kernel errors"],
        required_slots=[],
        optional_slots=["priority"],
        command_family="journalctl",
        description="Check kernel errors in system journal",
        doc_topic="journalctl"
    ),
    IntentSpec(
        domain="journalctl",
        operation="follow",
        lexical_hints=["follow logs", "follow the logs", "follow system journal", "follow journal logs", "tail system journal", "follow logs in real time", "stream journalctl"],
        required_slots=[],
        command_family="journalctl",
        description="Follow system journal in real time",
        doc_topic="journalctl"
    ),
    IntentSpec(
        domain="journalctl",
        operation="current_boot",
        lexical_hints=["current boot journal", "journal logs since boot", "logs for this boot", "current boot logs", "journalctl current boot"],
        required_slots=[],
        command_family="journalctl",
        description="Show journal logs for current boot",
        doc_topic="journalctl"
    ),

    # ── SYSTEMCTL SPECIFICATIONS ───────────────────────────────────────
    IntentSpec(
        domain="systemctl",
        operation="enable_and_start",
        lexical_hints=["enable and immediately start", "enable and start", "start and enable", "autostart service"],
        required_slots=["service"],
        command_family="systemctl",
        description="Enable and immediately start a systemd service",
        doc_topic="systemctl"
    ),
    IntentSpec(
        domain="systemctl",
        operation="restart_service",
        lexical_hints=["restart service", "restart daemon", "restart nginx", "restart the service"],
        required_slots=["service"],
        command_family="systemctl",
        description="Restart a systemd service",
    ),
    IntentSpec(
        domain="systemctl",
        operation="list_failed",
        lexical_hints=["list failed systemd services", "list failed services", "failed systemd units", "failed units", "list failed units"],
        required_slots=[],
        command_family="systemctl",
        description="List systemd units in failed state",
        doc_topic="systemctl"
    ),

    # ── FILESYSTEM / COREUTILS / BASH SPECIFICATIONS ──────────────────
    IntentSpec(
        domain="filesystem",
        operation="count_lines",
        lexical_hints=["count lines in", "number of lines in", "line count for", "how many lines in"],
        required_slots=["file"],
        optional_slots=["path"],
        command_family="coreutils",
        description="Count lines in a file",
        doc_topic="wc"
    ),
    IntentSpec(
        domain="filesystem",
        operation="sort_csv_column",
        lexical_hints=["sort csv", "sort by second column", "sort by column", "sort file by column"],
        required_slots=["file"],
        optional_slots=["column"],
        command_family="coreutils",
        description="Sort CSV by specific column numerically",
    ),
    IntentSpec(
        domain="filesystem",
        operation="text_replace",
        lexical_hints=["replace text in file", "substitute in file", "replace all occurrences in", "find and replace in"],
        required_slots=["file", "pattern", "replacement"],
        command_family="coreutils",
        description="Replace text patterns in a file",
    ),
    IntentSpec(
        domain="filesystem",
        operation="compare_files",
        lexical_hints=["compare two configuration files", "compare files", "diff two files", "show diff between files", "compare configuration files", "compare", "diff files"],
        required_slots=["file1", "file2"],
        command_family="coreutils",
        description="Compare two configuration files using diff",
        doc_topic="diff"
    ),
    IntentSpec(
        domain="filesystem",
        operation="watch_command",
        lexical_hints=["watch command output", "run command periodically", "watch periodically", "repeat command every"],
        required_slots=["command"],
        command_family="coreutils",
        description="Watch command output periodically",
        doc_topic="watch"
    ),
    IntentSpec(
        domain="filesystem",
        operation="create_symlink",
        lexical_hints=["create a symbolic link", "create symbolic link", "create symlink", "symlink pointing to", "link file to"],
        required_slots=["target", "linkname"],
        command_family="coreutils",
        description="Create a symbolic link",
        doc_topic="ln"
    ),
    IntentSpec(
        domain="filesystem",
        operation="kill_process_by_name",
        lexical_hints=["kill process by name", "kill all instances of", "terminate process by name", "pkill process", "killall"],
        required_slots=["process_name"],
        command_family="coreutils",
        description="Kill a process by name",
        doc_topic="pkill"
    ),
    IntentSpec(
        domain="filesystem",
        operation="download_file",
        lexical_hints=["download file with curl", "download file", "fetch file from url", "download url to file"],
        required_slots=["url"],
        optional_slots=["output"],
        command_family="coreutils",
        description="Download a file using curl or wget",
    ),
    IntentSpec(
        domain="filesystem",
        operation="create_tarball",
        lexical_hints=["create a tarball", "create tarball", "create compressed archive", "compress directory to tar.gz", "tar archive"],
        required_slots=["archive_name", "directory"],
        command_family="coreutils",
        description="Create a compressed tar archive",
    ),
    IntentSpec(
        domain="filesystem",
        operation="list_listening_ports",
        lexical_hints=["list listening network ports", "listening network ports", "listening ports", "open listening ports", "show listening ports"],
        required_slots=[],
        command_family="coreutils",
        description="List active listening network ports",
    ),
    IntentSpec(
        domain="filesystem",
        operation="preallocate_file",
        lexical_hints=["preallocate a file", "preallocate a test file", "allocate a 1gb test file", "allocate file named", "preallocate file", "fallocate file"],
        required_slots=["filename", "size"],
        command_family="coreutils",
        description="Safely preallocate a file of specified size",
        doc_topic="fallocate"
    ),
    IntentSpec(
        domain="filesystem",
        operation="identify_file_type",
        lexical_hints=["identify file type", "determine file type", "check mime type", "what kind of file is", "file type of"],
        required_slots=["file"],
        command_family="coreutils",
        description="Identify file type using file utility",
        doc_topic="file"
    ),
    IntentSpec(
        domain="filesystem",
        operation="print_env_var",
        lexical_hints=["print value of environment variable", "print environment variable", "print env var", "show environment variable", "echo env var"],
        required_slots=["variable"],
        command_family="coreutils",
        description="Print the value of an environment variable",
    ),
    IntentSpec(
        domain="filesystem",
        operation="checksum",
        lexical_hints=["compute sha256 checksum", "verify sha256 checksum", "checksum of file", "sha256 hash of"],
        required_slots=["file"],
        optional_slots=["algorithm"],
        command_family="coreutils",
        description="Compute cryptographic hash of a file",
        doc_topic="sha256sum"
    ),
    IntentSpec(
        domain="filesystem",
        operation="disk_usage",
        lexical_hints=["investigate disk usage", "disk usage", "show largest directories", "check disk space"],
        required_slots=[],
        optional_slots=["path"],
        command_family="coreutils",
        description="Investigate disk usage across directories",
    ),

    # ── GIT SPECIFICATIONS ─────────────────────────────────────────────
    IntentSpec(
        domain="git",
        operation="pull_rebase",
        lexical_hints=["git pull with rebase", "pull with rebase", "git pull --rebase", "pull upstream changes rebasing"],
        required_slots=[],
        command_family="git",
        description="Pull git changes using rebase",
    ),
    IntentSpec(
        domain="git",
        operation="stash",
        lexical_hints=["stash working directory changes", "stash changes", "git stash", "save uncommitted changes to stash"],
        required_slots=[],
        command_family="git",
        description="Stash uncommitted changes in git",
    ),
    IntentSpec(
        domain="git",
        operation="stash_pop",
        lexical_hints=["pop stashed changes", "apply stash and drop", "git stash pop", "restore stashed changes"],
        required_slots=[],
        command_family="git",
        description="Pop and apply stashed git changes",
    ),
    IntentSpec(
        domain="git",
        operation="create_branch",
        lexical_hints=["create and switch to new branch", "create new branch", "create git branch", "create branch", "checkout new branch", "switch to new branch"],
        required_slots=["branch"],
        command_family="git",
        description="Create and switch to a new git branch",
    ),
    IntentSpec(
        domain="git",
        operation="push_set_upstream",
        lexical_hints=["push branch and set upstream", "push and set upstream", "push branch to origin", "git push -u"],
        required_slots=["branch"],
        optional_slots=["remote"],
        command_family="git",
        description="Push branch to remote and set tracking upstream",
    ),
    IntentSpec(
        domain="git",
        operation="show_conflicts",
        lexical_hints=["diagnose git merge conflict", "show merge conflicts", "list unmerged files", "conflicted files in git"],
        required_slots=[],
        command_family="git",
        description="Show files with unmerged git merge conflicts",
    ),

    # ── TROUBLESHOOTING SPECIFICATIONS ─────────────────────────────────
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_oom",
        lexical_hints=["diagnose oom-killed process", "oom killed", "out of memory killed", "process killed by oom", "check oom events"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose OOM-killed processes from kernel buffer",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_disk_usage",
        lexical_hints=["diagnose disk full", "disk space running low", "no space left on device", "investigate full filesystem"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose low disk space and identify large files",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_ssh_service",
        lexical_hints=["diagnose ssh connection refused", "ssh connection refused", "ssh port 22 refused", "cannot connect to ssh"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose SSH service refusal on remote or local host",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_package_dep",
        lexical_hints=["diagnose failed package dependency", "broken package dependency", "package conflict dependency", "unmet dependencies"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose broken or conflicting package dependencies",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="find_broken_symlinks",
        lexical_hints=["find broken symlinks", "find broken symbolic links", "dangling symlinks", "identify broken symlinks"],
        required_slots=[],
        command_family="troubleshoot",
        description="Find broken or dangling symbolic links",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_io",
        lexical_hints=["diagnose slow disk i/o", "slow disk io", "disk latency diagnosis", "identify process causing disk io"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose slow disk I/O operations",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="port_collision",
        lexical_hints=["diagnose service start failure due to port conflict", "port conflict", "port collision", "address already in use", "port 80 already in use"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose service start failure due to port collision",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_firewall",
        lexical_hints=["diagnose firewall blocking incoming connection", "firewall blocking incoming", "incoming connection blocked by firewall", "firewall dropping packets"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose incoming connection dropped by firewall",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_segfault",
        lexical_hints=["diagnose segmentation fault", "segfault core dump", "process crashed with segfault", "signal 11 segfault"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose segmentation fault crashes via system logs",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_missing_python_module",
        lexical_hints=["diagnose python importerror", "modulenotfounderror", "importerror missing module", "no module named", "missing python module"],
        required_slots=[],
        optional_slots=["module"],
        command_family="troubleshoot",
        description="Diagnose Python ImportError for missing module",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_tls",
        lexical_hints=["diagnose tls certificate verification failure", "tls certificate failure", "ssl certificate expired", "certificate verification failure"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose TLS certificate verification or expiry issues",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_locale",
        lexical_hints=["diagnose locale encoding error", "locale encoding error", "utf-8 locale error", "unsupported locale settings"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose locale and UTF-8 encoding configuration errors",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_cron",
        lexical_hints=["diagnose cron job not executing", "cron job not running", "crontab failure", "scheduled cron job failed"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose cron execution failures via system journal",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_io_wait",
        lexical_hints=["diagnose high io wait", "high iowait", "high cpu iowait", "system freezing on disk io"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose high system I/O wait and identify heavy disk consumers",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_zombie_process",
        lexical_hints=["diagnose zombie processes", "find zombie processes", "defunct processes", "zombies in process table"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose and locate zombie or defunct processes",
    ),

    # ── ADDITIONAL TROUBLESHOOT SPECIFICATIONS (v3) ────────────────────
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_service_crash",
        lexical_hints=["service crash loop", "service restarting repeatedly", "diagnose service crash", "systemd service crash", "service failing repeatedly"],
        required_slots=[],
        optional_slots=["service", "since"],
        command_family="troubleshoot",
        description="Diagnose a repeatedly crashing systemd service via journal",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_failed_mount",
        lexical_hints=["failed mount unit", "systemd mount failed", "mount unit failure", "nfs mount failed", "view logs for failed unit"],
        required_slots=[],
        optional_slots=["unit"],
        command_family="troubleshoot",
        description="Diagnose a failed systemd mount unit via journal",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_pacman_signature",
        lexical_hints=["pacman signature error", "invalid or corrupted package", "signature verification failed", "update archlinux-keyring", "keyring signature error"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose pacman signature verification errors by refreshing keyring",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_docker_daemon",
        lexical_hints=["docker daemon error", "docker service error", "docker startup failure", "docker service failed", "view docker service error logs", "docker daemon startup failure"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose docker daemon startup failures via journal",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_nfs_mount",
        lexical_hints=["nfs stale file handle", "nfs mount error", "stale file handle", "nfs mount stale"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose NFS mount stale file handle errors",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_swap_exhaustion",
        lexical_hints=["swap exhaustion", "swap full", "no swap space", "check swap usage", "swap exhaustion on low ram"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose swap exhaustion on a low RAM host",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_thermal_throttling",
        lexical_hints=["cpu throttling", "thermal throttling", "cpu overheating", "cpu temperature", "thermal limit"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose CPU thermal throttling via sensors",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_dns_resolution",
        lexical_hints=["dns resolution timeout", "dns resolution failure", "dns lookup timeout", "failed coredns resolution", "diagnose dns"],
        required_slots=[],
        optional_slots=["domain", "server"],
        command_family="troubleshoot",
        description="Diagnose DNS resolution timeouts and failures using dig",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="verify_journal_integrity",
        lexical_hints=["verify journal integrity", "journal corruption", "journal verify", "system journal corruption", "journal corruption verification"],
        required_slots=[],
        command_family="troubleshoot",
        description="Verify integrity of systemd journal log files",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_core_dump_config",
        lexical_hints=["core dump pattern", "core dump configuration", "kernel core pattern", "coredump config"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose core dump pattern configuration via sysctl",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_load_average",
        lexical_hints=["system load average", "high load average", "diagnose load", "check load average", "system load with uptime"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose system load average via w or uptime",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_journal_disk_usage",
        lexical_hints=["journal disk usage", "journal disk size", "how much space does journal use", "journalctl disk usage"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose journal disk usage via journalctl --disk-usage",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_high_memory",
        lexical_hints=["high memory consumption", "memory usage by process", "top memory consuming processes", "process memory usage"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose high memory consumption by process tree",
    ),
    IntentSpec(
        domain="troubleshoot",
        operation="diagnose_oom",
        lexical_hints=["oom killer", "out of memory", "oom killed process", "process killed by oom", "oom termination", "diagnose why the node service suddenly died"],
        required_slots=[],
        command_family="troubleshoot",
        description="Diagnose OOM killer events in kernel ring buffer or journal",
    ),

    # ── ADDITIONAL SYSTEMCTL SPECIFICATIONS (v3) ───────────────────────
    IntentSpec(
        domain="systemctl",
        operation="list_timers",
        lexical_hints=["list active timers", "list systemd timers", "active timers", "systemctl timers"],
        required_slots=[],
        command_family="systemctl",
        description="List active systemd timer units",
    ),
    IntentSpec(
        domain="systemctl",
        operation="list_dependencies",
        lexical_hints=["list dependencies", "service dependency tree", "systemctl dependency", "list dependencies for unit"],
        required_slots=[],
        optional_slots=["unit"],
        command_family="systemctl",
        description="Show systemd unit dependency tree",
    ),
    IntentSpec(
        domain="systemctl",
        operation="check_dns_stub",
        lexical_hints=["check dns stub", "resolvectl status", "systemd resolved status", "dns server status"],
        required_slots=[],
        command_family="systemctl",
        description="Check systemd-resolved DNS stub resolver status",
    ),

    # ── ADDITIONAL PACMAN/ARCH SPECIFICATIONS (v3) ────────────────────
    IntentSpec(
        domain="pacman",
        operation="search_package",
        lexical_hints=["search package", "search for package", "query package in repo", "search repo", "search package in repos"],
        required_slots=[],
        optional_slots=["package"],
        command_family="pacman",
        description="Search for a package in pacman repositories",
    ),
    IntentSpec(
        domain="pacman",
        operation="query_foreign",
        lexical_hints=["list aur packages", "foreign packages", "query aur packages", "list foreign packages", "list packages installed from aur"],
        required_slots=[],
        command_family="pacman",
        description="List foreign/AUR packages installed via pacman -Qm",
    ),
    IntentSpec(
        domain="pacman",
        operation="check_db_lock",
        lexical_hints=["pacman database lock", "pacman db locked", "pacman lock file", "inspect processes holding pacman database lock", "check if pacman database has any locked processes"],
        required_slots=[],
        command_family="pacman",
        description="Check for processes holding the pacman database lock",
    ),
    IntentSpec(
        domain="pacman",
        operation="sysctl_read",
        lexical_hints=["sysctl read", "read sysctl parameter", "kernel sysctl", "inspect sysctl", "check kernel parameter"],
        required_slots=[],
        optional_slots=["key"],
        command_family="pacman",
        description="Read a kernel sysctl parameter value",
    ),
    IntentSpec(
        domain="pacman",
        operation="inspect_config",
        lexical_hints=["pacman config", "active repositories", "show repositories", "pacman.conf repos", "show active pacman repositories"],
        required_slots=[],
        command_family="pacman",
        description="Inspect pacman.conf for active repository sections",
    ),

    # ── ADDITIONAL JOURNALCTL SPECIFICATIONS (v3) ─────────────────────
    IntentSpec(
        domain="journalctl",
        operation="previous_boot",
        lexical_hints=["previous boot logs", "last boot journal", "boot minus one", "journalctl -b -1"],
        required_slots=[],
        command_family="journalctl",
        description="View journal logs from the previous boot",
    ),
    IntentSpec(
        domain="journalctl",
        operation="vacuum_time",
        lexical_hints=["vacuum journal by time", "clean journal older than", "remove old journal entries", "vacuum journal logs keeping 14 days", "clean journal log files"],
        required_slots=[],
        optional_slots=["days"],
        command_family="journalctl",
        description="Vacuum journal logs older than a given time threshold",
    ),
    IntentSpec(
        domain="journalctl",
        operation="kernel_grep",
        lexical_hints=["journal kernel grep", "filter kernel messages", "grep kernel journal", "show kernel messages containing", "kernel messages efi"],
        required_slots=[],
        optional_slots=["pattern"],
        command_family="journalctl",
        description="Filter kernel journal messages by grep pattern",
    ),

    # ── ADDITIONAL GCLOUD SPECIFICATIONS (v3) ─────────────────────────
    IntentSpec(
        domain="gcloud",
        operation="describe_network",
        lexical_hints=["describe vpc network", "describe compute network", "gcloud network describe", "vpc network details"],
        required_slots=[],
        optional_slots=["network"],
        command_family="gcloud",
        description="Describe a GCP VPC compute network",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_disks",
        lexical_hints=["list persistent disks", "list compute disks", "gcloud compute disks", "list persistent disks in compute"],
        required_slots=[],
        command_family="gcloud",
        description="List GCP compute persistent disks",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_configurations",
        lexical_hints=["list gcloud configurations", "gcloud config list", "active gcloud configuration", "gcloud configurations"],
        required_slots=[],
        command_family="gcloud",
        description="List active gcloud SDK configurations",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_run_services",
        lexical_hints=["list cloud run services", "list run services", "cloud run services list"],
        required_slots=[],
        optional_slots=["region"],
        command_family="gcloud",
        description="List Cloud Run services in a region",
    ),
    IntentSpec(
        domain="gcloud",
        operation="start_instance",
        lexical_hints=["start compute instance", "start instance", "gcloud start instance", "start stopped instance"],
        required_slots=[],
        optional_slots=["instance", "zone"],
        command_family="gcloud",
        description="Start a stopped GCP compute instance",
    ),
    IntentSpec(
        domain="gcloud",
        operation="describe_instance",
        lexical_hints=["describe compute instance", "instance details", "gcloud compute instances describe", "describe instance details"],
        required_slots=[],
        optional_slots=["instance", "zone"],
        command_family="gcloud",
        description="Describe a GCP compute instance",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_subnets",
        lexical_hints=["list subnets", "compute subnets", "list compute subnets", "vpc subnets", "list compute subnets in network"],
        required_slots=[],
        optional_slots=["network"],
        command_family="gcloud",
        description="List GCP compute VPC subnets",
    ),
    IntentSpec(
        domain="gcloud",
        operation="create_disk_snapshot",
        lexical_hints=["create disk snapshot", "snapshot disk", "create compute snapshot", "create persistent disk snapshot"],
        required_slots=[],
        optional_slots=["disk", "snapshot_name"],
        command_family="gcloud",
        description="Create a snapshot of a GCP compute persistent disk",
    ),
    IntentSpec(
        domain="gcloud",
        operation="list_run_revisions",
        lexical_hints=["list cloud run revisions", "run revisions list", "cloud run service revisions"],
        required_slots=[],
        optional_slots=["service", "region"],
        command_family="gcloud",
        description="List revisions for a Cloud Run service",
    ),

    # ── ADDITIONAL GH SPECIFICATIONS (v3) ─────────────────────────────
    IntentSpec(
        domain="gh",
        operation="workflow_run_list",
        lexical_hints=["list workflow runs", "view all workflows", "workflow status", "run list", "list runs"],
        required_slots=[],
        command_family="gh",
        description="List GitHub Actions workflow runs",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_checkout",
        lexical_hints=["checkout pr", "checkout pull request", "check out pr locally", "pr checkout"],
        required_slots=["pr_number"],
        command_family="gh",
        description="Checkout a pull request locally",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_list",
        lexical_hints=["list pull requests", "list prs", "show pull requests", "list open prs"],
        required_slots=[],
        optional_slots=["assignee", "label", "state"],
        command_family="gh",
        description="List pull requests with optional filters",
    ),
    IntentSpec(
        domain="gh",
        operation="auth_status",
        lexical_hints=["check gh auth status", "gh authentication status", "verify github login", "gh auth status"],
        required_slots=[],
        command_family="gh",
        description="Check GitHub CLI authentication status",
    ),
    IntentSpec(
        domain="gh",
        operation="repo_view",
        lexical_hints=["view repository", "repo view", "repository summary", "view repo status", "repo status summary"],
        required_slots=[],
        command_family="gh",
        intent_type="expansion",
        description="View repository summary status via gh repo view",
    ),
    IntentSpec(
        domain="gh",
        operation="workflow_run_rerun",
        lexical_hints=["rerun failed workflow", "rerun workflow run", "re-run failed jobs", "rerun failed workflow jobs"],
        required_slots=["run_id"],
        optional_slots=["failed_only"],
        command_family="gh",
        intent_type="expansion",
        description="Rerun a failed GitHub Actions workflow run",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_close",
        lexical_hints=["close pr without merging", "close pull request", "discard pr"],
        required_slots=["pr_number"],
        command_family="gh",
        description="Close a pull request without merging",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_checks",
        lexical_hints=["pr checks summary", "pr status checks", "check status for pr", "view pr checks"],
        required_slots=["pr_number"],
        command_family="gh",
        description="View CI/CD check status summary for a PR",
    ),
    IntentSpec(
        domain="gh",
        operation="issue_reopen",
        lexical_hints=["reopen issue", "re-open closed issue"],
        required_slots=["issue_number"],
        command_family="gh",
        description="Reopen a previously closed issue",
    ),
    IntentSpec(
        domain="gh",
        operation="release_view",
        lexical_hints=["view release", "list release assets", "release details", "release view"],
        required_slots=[],
        optional_slots=["tag"],
        command_family="gh",
        description="View release details and assets",
    ),
    IntentSpec(
        domain="gh",
        operation="workflow_view",
        lexical_hints=["view workflow file", "workflow view", "view specific workflow"],
        required_slots=[],
        optional_slots=["workflow"],
        command_family="gh",
        description="View a specific GitHub Actions workflow file",
    ),
    IntentSpec(
        domain="gh",
        operation="pr_create",
        lexical_hints=["create pull request", "create draft pr", "create pr", "open pull request"],
        required_slots=[],
        optional_slots=["draft", "title"],
        command_family="gh",
        description="Create a new pull request (optionally as draft)",
    ),

    # ── ADDITIONAL FILESYSTEM SPECIFICATIONS (v3) ─────────────────────
    IntentSpec(
        domain="filesystem",
        operation="docker_logs",
        lexical_hints=["check docker logs", "inspect container logs", "docker logs", "view container logs", "check the logs of"],
        required_slots=[],
        optional_slots=["container"],
        command_family="filesystem",
        description="View container log output via docker logs",
    ),
    IntentSpec(
        domain="filesystem",
        operation="find_broken_symlinks",
        lexical_hints=["find broken symlinks", "broken symbolic links", "dangling symlinks", "find broken links"],
        required_slots=[],
        optional_slots=["path"],
        command_family="filesystem",
        description="Find dangling/broken symbolic links under a given path",
    ),
    IntentSpec(
        domain="filesystem",
        operation="delete_temp_files",
        lexical_hints=["delete temp files", "remove temporary files", "clean up tmp files", "delete cache files"],
        required_slots=[],
        optional_slots=["path"],
        command_family="filesystem",
        description="Delete temporary or cache files from user directory",
    ),
    IntentSpec(
        domain="filesystem",
        operation="inspect_partition_table",
        lexical_hints=["inspect partition table", "check partition table", "view partition table", "fdisk list partitions"],
        required_slots=[],
        command_family="filesystem",
        description="Inspect disk partition table safely (read-only)",
    ),
    IntentSpec(
        domain="filesystem",
        operation="show_uptime",
        lexical_hints=["check system uptime", "system uptime", "uptime and load", "check uptime"],
        required_slots=[],
        command_family="filesystem",
        description="Show system uptime and load average",
    ),
    IntentSpec(
        domain="filesystem",
        operation="rerun_failed_tests",
        lexical_hints=["rerun failed tests", "run only failed tests", "rerun only the failed test", "pytest rerun failed", "last failed tests"],
        required_slots=[],
        optional_slots=["framework"],
        command_family="filesystem",
        description="Rerun only the most recently failed tests",
    ),
    IntentSpec(
        domain="filesystem",
        operation="count_words",
        lexical_hints=["count words", "word count", "wc -w", "count words in file"],
        required_slots=[],
        optional_slots=["file"],
        command_family="filesystem",
        description="Count words in a file using wc -w",
    ),
    IntentSpec(
        domain="filesystem",
        operation="list_block_devices",
        lexical_hints=["list block devices", "show block devices", "lsblk", "block device info", "list block devices showing filesystem"],
        required_slots=[],
        command_family="filesystem",
        intent_type="expansion",
        description="List block devices with filesystem info via lsblk",
    ),
    IntentSpec(
        domain="filesystem",
        operation="show_ip_routing_table",
        lexical_hints=["ip routing table", "show routing table", "kernel routing table", "view routing table"],
        required_slots=[],
        command_family="filesystem",
        intent_type="expansion",
        description="Show IP routing table via ip route or route -n",
    ),
    IntentSpec(
        domain="filesystem",
        operation="list_docker_containers",
        lexical_hints=["list running docker containers", "list docker containers", "running containers", "active docker containers"],
        required_slots=[],
        command_family="filesystem",
        intent_type="expansion",
        description="List running docker containers via docker ps",
    ),
    IntentSpec(
        domain="filesystem",
        operation="network_socket_stats",
        lexical_hints=["network socket statistics", "socket statistics", "ss -s", "socket stats summary"],
        required_slots=[],
        command_family="filesystem",
        intent_type="expansion",
        description="Show summary network socket statistics via ss -s",
    ),
    IntentSpec(
        domain="filesystem",
        operation="show_partition_table",
        lexical_hints=["show disk partition table", "partition table", "parted list", "disk partition table with parted"],
        required_slots=[],
        command_family="filesystem",
        intent_type="expansion",
        description="Show disk partition table via parted -l",
    ),

    # ── SAFETY / CONTROLLED ELEVATION SPECIFICATIONS ──────────────────
    IntentSpec(
        domain="safety",
        operation="safe_disk_formatting",
        lexical_hints=["format usb drive", "format external drive", "format usb", "create ext4 filesystem on usb"],
        required_slots=[],
        destructive=True,
        command_family="safety",
        description="Safely format an external USB drive with elevated risk",
    ),
    IntentSpec(
        domain="safety",
        operation="safe_ssh_keygen",
        lexical_hints=["generate ssh key pair", "create ssh key", "generate ed25519 ssh key", "ssh-keygen"],
        required_slots=[],
        command_family="safety",
        description="Generate SSH key pair safely without overwriting",
    ),
    IntentSpec(
        domain="safety",
        operation="journal_vacuum",
        lexical_hints=["safe journal vacuum", "vacuum journal logs", "shrink journal size", "vacuum system journal"],
        required_slots=[],
        command_family="safety",
        description="Safely vacuum journal logs without deleting raw log files",
    ),
    IntentSpec(
        domain="safety",
        operation="safe_mysql_password",
        lexical_hints=["change mysql root password", "set mysql root password", "update mysql root password"],
        required_slots=[],
        command_family="safety",
        description="Safely change MySQL root password without plaintext cli exposure",
    ),
    IntentSpec(
        domain="safety",
        operation="safe_visudo",
        lexical_hints=["edit sudoers file", "safely edit sudoers", "visudo"],
        required_slots=[],
        command_family="safety",
        description="Safely edit sudoers configuration file with visudo",
    ),
    IntentSpec(
        domain="safety",
        operation="safe_swapoff",
        lexical_hints=["disable swap space", "turn off swap", "swapoff safely"],
        required_slots=[],
        command_family="safety",
        description="Safely disable swap space",
    ),

    # ── INTERACTION / CLARIFY / TYPO SPECIFICATIONS ────────────────────
    IntentSpec(
        domain="interaction",
        operation="clarify",
        lexical_hints=[
            "delete the files", "clean up the system", "remove the directory",
            "kill the process", "fix the issue", "reset everything", "delete files",
            "clean up files", "clean files", "remove files"
        ],
        required_slots=[],
        command_family="interaction",
        description="Ambiguous user request requiring clarification",
    ),
    IntentSpec(
        domain="interaction",
        operation="no_action",
        lexical_hints=[],
        required_slots=[],
        command_family="interaction",
        description="Passive terminal state requiring no model action",
    ),
    IntentSpec(
        domain="interaction",
        operation="typo_kubectl",
        lexical_hints=["kubctl", "kc get"],
        required_slots=[],
        command_family="interaction",
        description="Typo correction for kubectl commands",
    ),
    IntentSpec(
        domain="interaction",
        operation="typo_git",
        lexical_hints=["git stats", "git stauts", "git sttus"],
        required_slots=[],
        command_family="interaction",
        description="Typo correction for git status commands",
    ),
    IntentSpec(
        domain="interaction",
        operation="typo_docker",
        lexical_hints=["dockr", "dokcer"],
        required_slots=[],
        command_family="interaction",
        description="Typo correction for docker commands",
    ),
    IntentSpec(
        domain="interaction",
        operation="ghost_completion_docker",
        lexical_hints=["docker exec -it"],
        required_slots=[],
        command_family="interaction",
        description="Ghost completion for docker exec",
    ),
    IntentSpec(
        domain="interaction",
        operation="ghost_completion_pacman",
        lexical_hints=["sudo pacman -S ri"],
        required_slots=[],
        command_family="interaction",
        description="Ghost completion for pacman package install",
    ),
]


class IntentRegistry:
    """Central registry of IntentSpecs for cAIman Terminal."""

    def __init__(self, specs: Optional[List[IntentSpec]] = None):
        self._specs = list(specs) if specs is not None else list(CANONICAL_INTENT_SPECS)
        self._by_key: Dict[Tuple[str, str], IntentSpec] = {
            (s.domain.lower(), s.operation.lower()): s for s in self._specs
        }
        self._by_op: Dict[str, IntentSpec] = {
            s.operation.lower(): s for s in self._specs
        }

    def get_spec(self, domain: str, operation: str) -> Optional[IntentSpec]:
        return self._by_key.get((domain.lower(), operation.lower()))

    def find_by_operation(self, operation: str) -> Optional[IntentSpec]:
        return self._by_op.get(operation.lower())

    def all_specs(self) -> List[IntentSpec]:
        return list(self._specs)

    def specs_for_domain(self, domain: str) -> List[IntentSpec]:
        d = domain.lower()
        return [s for s in self._specs if s.domain.lower() == d]

    def specs_for_family(self, command_family: str) -> List[IntentSpec]:
        f = command_family.lower()
        return [s for s in self._specs if s.command_family and s.command_family.lower() == f]
